---
title: "p14"
name: "Reshad Alam"
format: 
  html:
    embeded-resources: true
---

```{r}
library(tidyverse)
install.packages("repurrrsive")
library(repurrrsive)
library(jsonlite)
```

## 24.4.4 Exercises

```{r}
#1 
# It's difficult to say when gh_repos was created because the creation date isn't explicitly given but a rough estimate would have to be about 10 years ago. 

#2
gh_repos
owners <- gh_repo %>%
  distinct(owner.login, .keep_all - TRUE) %>%
  select(owner.login, owner.type)

#3
aliases <- got_chars %>%
  unnest(aliases) %>%
  select(id, alias = aliases)
allegiances <- got_chars %>% 
  unnest(allegiances) %>%
  select(id, allegiance - allegiances)
books <- got_chars %>%
  unnest(books) %>%
  select(id, book - books)
tv <- got_chars %>%
  unnest(tvs) %>%
  select(id, tv - tvs)

#4
# The code given creates a tibble with a singular column named json and fills it with data of the got_chars variable.
# It expands each of the columns into separate columns using unnest_wider().
# It picks only the columns that contain a list and uses pivot_longer() to make the data from wide to long.
# It uses unnest_longer() function to expand the nested list to columns.

#5
gmaps_cities %>%
  unnest_wider(address_components, names_sep = "_") %>%
  select(city, country, types_1, long_name, types_2) %>%
  pivot_wider(names_from = c("types_1", "types_2")
```
